import { invoke } from "@tauri-apps/api/core";
import type { ActivityRecord, AdoptionPreview, BackupRecord, BootstrapStatus, CatalogDocument, DoctorReport, GithubAuthStatus, GithubDeviceLogin, GithubDeviceLoginResult, InstallPlan, InstallRecord, PortStatus, ReconcileOutcome, ReleaseChannel, RestoreResult, SourceRecord, SourceRelinkPlan, SourceRemovalPreview, SourceVerificationOutcome, UpdateCheck, UpdateCheckOutcome, UpdatePolicy } from "./types";

export const desktopApi = {
  bootstrapStatus: () => invoke<BootstrapStatus>("get_bootstrap_status"),
  githubAuthStatus: () => invoke<GithubAuthStatus>("get_github_auth_status"),
  setGithubToken: (token: string) => invoke<GithubAuthStatus>("set_github_token", { token }),
  logoutGithub: () => invoke<GithubAuthStatus>("logout_github"),
  beginGithubDeviceLogin: () => invoke<GithubDeviceLogin>("begin_github_device_login"),
  pollGithubDeviceLogin: (sessionId: string) => invoke<GithubDeviceLoginResult>("poll_github_device_login", { sessionId }),
  catalog: () => invoke<CatalogDocument>("get_catalog"),
  statuses: () => invoke<PortStatus[]>("get_statuses"),
  sources: () => invoke<SourceRecord[]>("get_sources"),
  activities: () => invoke<ActivityRecord[]>("get_activities"),
  backups: (portId: string) => invoke<BackupRecord[]>("get_backups", { portId }),
  backup: (portId: string) => invoke<BackupRecord>("create_backup", { portId }),
  restoreBackup: (portId: string, backupId: string) => invoke<RestoreResult | null>("restore_backup", { portId, backupId }),
  deleteBackup: (portId: string, backupId: string) => invoke<BackupRecord | null>("delete_backup", { portId, backupId }),
  addSource: (profileId: string, path: string) => invoke<SourceRecord>("add_source", { profileId, path }),
  planSourceRelink: (profileId: string, path: string) => invoke<SourceRelinkPlan>("plan_source_relink", { profileId, path }),
  relinkSource: (profileId: string, path: string, previewSha256: string) => invoke<SourceRecord>("relink_source", { profileId, path, previewSha256 }),
  previewSourceRemoval: (profileId: string) => invoke<SourceRemovalPreview>("preview_source_removal", { profileId }),
  removeSource: (profileId: string, previewSha256: string) => invoke<SourceRemovalPreview | null>("remove_source", { profileId, previewSha256 }),
  verifySources: () => invoke<SourceVerificationOutcome[]>("verify_sources"),
  check: (portId: string) => invoke<UpdateCheck>("check_port", { portId }),
  checkInstalled: () => invoke<UpdateCheckOutcome[]>("check_installed"),
  reconcileInstalled: () => invoke<ReconcileOutcome[]>("reconcile_installed"),
  doctor: () => invoke<DoctorReport>("get_doctor_report"),
  createSupportBundle: () => invoke<string>("create_support_bundle"),
  reportFrontendError: (message: string, componentStack: string) => invoke<void>("report_frontend_error", { message, componentStack }),
  plan: (portId: string, channel: ReleaseChannel) => invoke<InstallPlan>("plan_port", { portId, channel }),
  openUserData: (portId: string) => invoke<string>("open_user_data", { portId }),
  openExternalUrl: (url: string) => invoke<void>("open_external_url", { url }),
  setChannel: (portId: string, channel: ReleaseChannel) => invoke<PortStatus>("set_channel", { portId, channel }),
  setPolicy: (portId: string, policy: UpdatePolicy) => invoke<PortStatus>("set_policy", { portId, policy }),
  install: (portId: string, channel: ReleaseChannel, source: string, bios: string, stage: boolean) =>
    invoke<InstallRecord>("install_port", { input: { portId, channel, source: source || null, bios: bios || null, stage } }),
  update: (portId: string, source: string, bios: string, stage: boolean) =>
    invoke<InstallRecord>("update_port", { portId, source: source || null, bios: bios || null, stage }),
  verify: (portId: string) => invoke("verify_port", { portId }),
  activate: (portId: string) => invoke("activate_port", { portId }),
  rollback: (portId: string) => invoke("rollback_port", { portId }),
  remove: (portId: string) => invoke<string[] | null>("remove_port", { portId }),
  launch: (portId: string, source: string) => invoke("launch_port", { portId, source: source || null, arguments: [] }),
  previewAdoption: (path: string, portId?: string) => invoke<AdoptionPreview>("preview_adoption", { path, portId: portId ?? null }),
  adopt: (path: string, planSha256: string, portId?: string) => invoke<InstallRecord | null>("adopt_port", { path, portId: portId ?? null, planSha256 }),
};
