// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  settings: {
    language: {
      current: "Portcove is using {{language}}.";
      description: "Choose the language Portcove uses on this device.";
      engineering: "العربية (اختبار هندسي)";
      english: "English";
      eyebrow: "LANGUAGE";
      pickerLabel: "Display language";
      richProof: "Keyboard focus stays <strong>where you left it</strong> when the language changes.";
      sample_one: "{{count}} localized message is ready.";
      sample_other: "{{count}} localized messages are ready.";
      saveFailed: "Portcove could not save the language. Your previous choice is still active.";
      saved: "Language saved.";
      saving: "Saving language…";
      system: "System default";
      title: "Language";
      unavailable: "Translation unavailable";
    };
  };
}
