// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "settings": {
    "language": {
      "applyFailed": "Language preference saved, but Portcove couldn't confirm the display switch. Reopen Settings to check.",
      "current": "Current language: {{language}}.",
      "description": "English is the supported display language. System default uses English when your system language is unavailable.",
      "engineering": "Arabic (engineering preview)",
      "english": "English",
      "eyebrow": "LANGUAGE",
      "loadFailed": "Couldn't load your language preference. Using {{language}} for now.",
      "pickerLabel": "Display language",
      "previewDescription": "This preview changes the language panel and text direction. The rest of Portcove remains in English.",
      "previewTitle": "Language preview",
      "richProof": "Keyboard focus stays <strong>where you left it</strong> when the language changes.",
      "sample_one": "{{count}} localized message is ready.",
      "sample_other": "{{count}} localized messages are ready.",
      "saveFailed": "Couldn't save the language. Your current language is unchanged.",
      "saved": "Language saved.",
      "saving": "Saving language…",
      "system": "System default",
      "title": "Language",
      "unavailable": "Translation unavailable"
    }
  }
}
